#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""OPT-IN: encode a BREAK bank of one-bar WAVs (a folder with bank.txt, as written by
tools/import_breaks.py) as IMA ADPCM (tools/sampleio.py: the sample slots' format), into the
header the firmware compiles in, instead of the default 909-rendered loops.

  X0X_BREAK_BANK=build/breaks ./build.sh            (what build.py runs:)
  tools/gen_break_bank.py DIR OUT.h

Nothing in this tree is such a folder: what goes in a bank, and whether a firmware built
with it may be distributed, is the builder's decision. Fails if the bank exceeds BUDGET
bytes of flash (the app slot has to hold it)."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sampleio as sio  # noqa: E402

SRC = Path(__file__).resolve().parents[1]
BUDGET = 128 * 1024              # the app slot's room for a bank (the 909 loops it replaces + headroom)


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    DIR, out = Path(sys.argv[1]), Path(sys.argv[2])
    rows = [ln.split() for ln in (DIR / "bank.txt").read_text().splitlines() if ln and not ln.startswith("#")]
    h = ["/* Generated by tools/gen_break_bank.py -- do not edit. The BREAK part's built-in loops:",
         " * one bar each, IMA ADPCM from predictor 0 / index 0, mono, 22050 Hz, from",
         f" * {DIR.name}/ (an opt-in bank). */", "#pragma once", "#include <stdint.h>",
         f"#define X0X_NBREAKS {len(rows)}", "#define X0X_BREAK_RATE 22050u", ""]
    total = 0
    tab = []
    for i, (name, bars, *_rest) in enumerate(rows):
        sr, x = sio.read_any_wav(DIR / f"{name}.wav")
        if sr != 22050:
            raise SystemExit(f"{name}.wav: {sr} Hz, want 22050 (run tools/import_breaks.py)")
        data, _ = sio.ima_encode([int(round(max(-1.0, min(1.0, v)) * 32767)) for v in x], 0)
        total += len(data)
        h.append(f"static const uint8_t X0X_BREAK_{i}[{len(data)}] = {{")
        for k in range(0, len(data), 24):
            h.append("    " + ",".join(str(b) for b in data[k:k + 24]) + ",")
        h.append("};")
        tab.append(f'    {{"{name}", X0X_BREAK_{i}, {len(x)}u, {int(bars)}}},')
    h += ["", "typedef struct { const char *name; const uint8_t *adpcm; uint32_t n; uint8_t bars; } x0x_break_t;",
          "static const x0x_break_t X0X_BREAKS[X0X_NBREAKS] = {", *tab, "};", ""]
    if total > BUDGET:
        raise SystemExit(f"break bank: {total} B exceeds the {BUDGET} B flash budget; drop a loop in import_breaks.py")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(h))
    print(f"break bank: {len(rows)} loops, {total} B of flash (budget {BUDGET})")


if __name__ == "__main__":
    main()
