#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Cut one bar of each chosen loop from BB Gen's sample folder (mestela/schwung-breakbeat),
mono, 22050 Hz, 16-bit, into OUTDIR (default build/breaks, outside version control). Use the
result for an OPT-IN built-in bank (X0X_BREAK_BANK=build/breaks ./build.sh), or upload it
(tools/upload_breaks.py). The default firmware ships no recorded breaks.

  tools/import_breaks.py [BBGEN_SAMPLES_DIR [OUTDIR]]    (default ../schwung-breakbeat/samples)

A loop's bar count is the one (1, 2 or 4) that puts its tempo nearest 120 BPM inside
80..180, the same rule the firmware uses for user loops; the first bar is kept."""
import struct
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sampleio as sio  # noqa: E402

SRC = Path(__file__).resolve().parents[1]
RATE = 22050

# (BB Gen file, name on the device <= 6 chars): the bank order is the SLOT order on the device
BANK = [("amen01.wav", "AMEN"), ("think.wav", "THINK"), ("funkydrummer.wav", "FUNKY"),
        ("apache.wav", "APACHE"), ("kool.wav", "KOOL"), ("sesame.wav", "SESAME")]
# a built-in bank: 7 (with king.wav) came to 161 KB against gen_break_bank.py's 150 KB budget


def bars_of(seconds):
    best = None
    for b in (1, 2, 4):
        bpm = b * 240.0 / seconds
        if 80 <= bpm <= 180 and (best is None or abs(bpm - 120) < abs(best[1] - 120)):
            best = (b, bpm)
    return best or (1, 240.0 / seconds)


def write_wav(path, x, rate):
    pcm = b"".join(struct.pack("<h", max(-32768, min(32767, int(round(v * 32767))))) for v in x)
    path.write_bytes(b"RIFF" + struct.pack("<I", 36 + len(pcm)) + b"WAVEfmt " +
                     struct.pack("<IHHIIHH", 16, 1, 1, rate, rate * 2, 2, 16) + b"data" + struct.pack("<I", len(pcm)) + pcm)


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else SRC.parent / "schwung-breakbeat" / "samples"
    OUT = Path(sys.argv[2]) if len(sys.argv) > 2 else SRC / "build" / "breaks"
    OUT.mkdir(parents=True, exist_ok=True)
    lines = ["# name  bars  source-bpm  source  (generated by tools/import_breaks.py)"]
    for fn, name in BANK:
        sr, x = sio.read_any_wav(src / fn)
        bars, bpm = bars_of(len(x) / sr)
        one = x[: int(round(len(x) / bars))]                  # the first bar
        y = sio.resample(one, sr, RATE)
        pk = max(1e-9, max(abs(v) for v in y))
        y = [v * (0.95 / pk) for v in y]                      # normalised, like the slots' loader would
        write_wav(OUT / f"{name}.wav", y, RATE)
        lines.append(f"{name} 1 {bpm:.1f} {fn}")
        print(f"{name:7s} {fn:18s} {bars} bar(s) at {bpm:5.1f} BPM -> 1 bar, {len(y)} samples")
    (OUT / "bank.txt").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
